- name: install django 1.6.5
  pip: name=django version=1.6.5 virtualenv=/root/ENV

- name: create project directory
  file: path=/usr/share/opencomputemanager state=directory

- name: create project
  command: /root/ENV/bin/django-admin.py startproject opencomputemanager /usr/share/opencomputemanager 
